# Verify rule files with HTML Tidy

name: Verify rule files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    - name: Install xmllint
      run: |
         sudo apt-get update
         sudo apt-get install libxml2-utils
    - name: Install HTML Tidy
      run: |
         wget https://github.com/htacg/tidy-html5/releases/download/5.8.0/tidy-5.8.0-Linux-64bit.deb
         sudo dpkg -i tidy-5.8.0-Linux-64bit.deb
    - name: Verify rule files
      run: bash ./cxx-sensors/src/tools/check_rules.sh

